name: magic_plan
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  auto_route: ^7.8.4
  talker_flutter: ^3.6.0
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
